# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
   include:
     - main
 paths:
   exclude:
     - README.md
     - cicd/azDo/ci.yaml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: sqlunittest

steps:
- task: PowerShell@2
  displayName: 'Transform appsettings.json file from variable group '
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $json = Get-Content "$(Build.SourcesDirectory)/src/SqlUnitTestDemo/appsettings.json" | ConvertFrom-Json 
      $json.AzureResources.TenantId = '$(AzureResources.TenantId)'
      $json.AzureResources.ServicePrincipleClientId = '$(AzureResources.ServicePrincipleClientId)'
      $json.AzureResources.ServicePrincipleClientSecret = '$(AzureResources.ServicePrincipleClientSecret)'
      $json | ConvertTo-Json | Out-File "$(Build.SourcesDirectory)/src/SqlUnitTestDemo/appsettings.json"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
  displayName: 'Restore NuGet packages'

#run test
- task: DotNetCoreCLI@2
  displayName: 'run end to end test'
  inputs:
    command: 'test'
    testRunTitle: 'Run Tests'
    projects: '**/src/SqlUnitTestDemo/SqlUnitTestDemo.csproj'
    

